#############################################################################
# Generated by PAGE version 4.11
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family @MingLiU_HKSCS-ExtB -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI Black} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m39" -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 588x552
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 2736 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "The Cipher Brief"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m39
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#ffffff} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    canvas $top.can40 \
        -background {#ffffff} -closeenough 1.0 -height 183 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#ffffff} \
        -selectforeground {#000000} -width 373 
    vTcl:DefineAlias "$top.can40" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -activebackground {#ffffff} -background {#ffffff} \
        -disabledforeground {#a3a3a3} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -text {Encrypt File } 
    vTcl:DefineAlias "$top.lab41" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text {Decrypt File} 
    vTcl:DefineAlias "$top.lab42" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {select file} 
    vTcl:DefineAlias "$top.but43" "select_enc" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {select file} 
    vTcl:DefineAlias "$top.but45" "select_dec" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent46" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent47" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent48" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent49" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent50" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent51" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent52" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent53" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8080ff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ENCRYPT 
    vTcl:DefineAlias "$top.but54" "enc_b" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8080ff} -disabledforeground {#ffffff} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text DECRYPT 
    vTcl:DefineAlias "$top.but55" "dec_b" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab56 \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Enter Encryption Code :} 
    vTcl:DefineAlias "$top.lab56" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Enter Decryption Code:} 
    vTcl:DefineAlias "$top.lab57" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text (0-25) 
    vTcl:DefineAlias "$top.lab58" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-25) 
    vTcl:DefineAlias "$top.lab59" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-29) 
    vTcl:DefineAlias "$top.lab60" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-9) 
    vTcl:DefineAlias "$top.lab61" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-25) 
    vTcl:DefineAlias "$top.lab62" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-25) 
    vTcl:DefineAlias "$top.lab63" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-29) 
    vTcl:DefineAlias "$top.lab64" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (0-9) 
    vTcl:DefineAlias "$top.lab65" "Label5" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes67 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {status : Succcessfull or Failed} -width 180 
    vTcl:DefineAlias "$top.mes67" "Msg_enc" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes68 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {status : Succcessfull or Failed} -width 180 
    vTcl:DefineAlias "$top.mes68" "Msg_dec" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can40 \
        -in $top -x 110 -y 10 -width 373 -relwidth 0 -height 183 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 80 -y 230 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 350 -y 230 -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 80 -y 260 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 360 -y 260 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 50 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 100 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 150 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 200 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 340 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 390 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 440 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 490 -y 320 -width 44 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 70 -y 380 -width 157 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 370 -y 380 -width 157 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 90 -y 290 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 370 -y 290 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 50 -y 340 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 100 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab60 \
        -in $top -x 150 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab61 \
        -in $top -x 200 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab62 \
        -in $top -x 340 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab63 \
        -in $top -x 390 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab64 \
        -in $top -x 440 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.lab65 \
        -in $top -x 490 -y 340 -width 37 -height 21 -anchor nw \
        -bordermode inside 
    place $top.mes67 \
        -in $top -x 60 -y 450 -width 180 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes68 \
        -in $top -x 360 -y 450 -width 180 -height 23 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

