#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Sep 24, 2018 07:30:11 PM

import sys
import tkinter as tk  
from PIL import ImageTk
from tkinter import Tk
from tkinter.filedialog import askopenfilename
import cipher as cp

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import TCB_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = The_Cipher_Brief (root)
    TCB_support.init(root, top)
    root.wm_iconbitmap('TCBIcon.ico')
    root.mainloop()

w = None
def create_The_Cipher_Brief(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = The_Cipher_Brief (w)
    TCB_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_The_Cipher_Brief():
    global w
    w.destroy()
    w = None


class The_Cipher_Brief:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family @MingLiU_HKSCS-ExtB -size 14 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("588x552")
        top.title("The Cipher Brief")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = Menu(top,font="TkMenuFont",bg='#ffffff',fg=_fgcolor)
        top.configure(menu = self.menubar)
        
        def select_f_e():
            Tk().withdraw() 
            filename = askopenfilename()
            if len(filename) != 0:
                encMsg.set("Encrypting Status : '"+filename+"' is selected for Encryption")    
            fname.set(filename)
            
        def select_f_d():
            Tk().withdraw() 
            filename = askopenfilename()
            if len(filename) != 0:
                decMsg.set("Decrypting Status : '"+filename+"' is selected for Decryption")
            fname.set(filename)
            
        def enc():
            filename = fname.get()
            k1=e1.get()
            k2=e2.get()
            k3=e3.get()
            k4=e4.get()
            cp.Encryp(filename,k1,k2,k3,k4)
            encMsg.set("Encrypting Status : '"+filename+"' successfully Encrypted")
            
            
        
        def dec():
            filename = fname.get()
            k1=d1.get()
            k2=d2.get()
            k3=d3.get()
            k4=d4.get()
            cp.Decryp(filename,k1,k2,k3,k4)
            decMsg.set("Decrypting Status : '"+filename+"' successfully Decrypted")
            
            
        
        encMsg = StringVar()
        decMsg = StringVar()
        fname = StringVar()
        
        e1=IntVar()
        e2=IntVar()
        e3=IntVar()
        e4=IntVar()
        
        d1=IntVar()
        d2=IntVar()
        d3=IntVar()
        d4=IntVar()  
        
        
        self.Canvas1 = Canvas(top)
        self.image = ImageTk.PhotoImage(file = "cblogo.png")
        self.Canvas1.create_image(10, 10, image = self.image, anchor = NW)
        self.Canvas1.place(relx=0.24, rely=0.02, relheight=0.41, relwidth=0.62)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#ffffff")
        self.Canvas1.configure(selectforeground="#000000")
        self.Canvas1.configure(width=373)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.14, rely=0.42, height=25, width=149)
        self.Label1.configure(activebackground="#ffffff")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Encrypt File''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.6, rely=0.42, height=25, width=138)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Decrypt File''')

        self.select_enc = Button(top,command=select_f_e)
        self.select_enc.place(relx=0.14, rely=0.47, height=24, width=147)
        self.select_enc.configure(activebackground="#d9d9d9")
        self.select_enc.configure(activeforeground="#000000")
        self.select_enc.configure(background="#d9d9d9")
        self.select_enc.configure(disabledforeground="#a3a3a3")
        self.select_enc.configure(foreground="#000000")
        self.select_enc.configure(highlightbackground="#d9d9d9")
        self.select_enc.configure(highlightcolor="black")
        self.select_enc.configure(pady="0")
        self.select_enc.configure(text='''select file''')
        self.select_enc.configure(width=147)

        self.select_dec = Button(top,command=select_f_d)
        self.select_dec.place(relx=0.61, rely=0.47, height=24, width=147)
        self.select_dec.configure(activebackground="#d9d9d9")
        self.select_dec.configure(activeforeground="#000000")
        self.select_dec.configure(background="#d9d9d9")
        self.select_dec.configure(disabledforeground="#a3a3a3")
        self.select_dec.configure(foreground="#000000")
        self.select_dec.configure(highlightbackground="#d9d9d9")
        self.select_dec.configure(highlightcolor="black")
        self.select_dec.configure(pady="0")
        self.select_dec.configure(text='''select file''')
        self.select_dec.configure(width=147)

        self.Entry1 = Entry(top,textvariable=e1)
        self.Entry1.place(relx=0.09, rely=0.58,height=20, relwidth=0.07)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=44)

        self.Entry2 = Entry(top,textvariable=e2)
        self.Entry2.place(relx=0.17, rely=0.58,height=20, relwidth=0.07)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=44)

        self.Entry3 = Entry(top,textvariable=e3)
        self.Entry3.place(relx=0.26, rely=0.58,height=20, relwidth=0.07)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(width=44)

        self.Entry4 = Entry(top,textvariable=e4)
        self.Entry4.place(relx=0.34, rely=0.58,height=20, relwidth=0.07)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(width=44)

        self.Entry5 = Entry(top,textvariable=d1)
        self.Entry5.place(relx=0.58, rely=0.58,height=20, relwidth=0.07)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=44)

        self.Entry6 = Entry(top,textvariable=d2)
        self.Entry6.place(relx=0.66, rely=0.58,height=20, relwidth=0.07)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(width=44)

        self.Entry7 = Entry(top,textvariable=d3)
        self.Entry7.place(relx=0.75, rely=0.58,height=20, relwidth=0.07)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(width=44)

        self.Entry8 = Entry(top,textvariable=d4)
        self.Entry8.place(relx=0.83, rely=0.58,height=20, relwidth=0.07)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(width=44)

        self.enc_b = Button(top,command=enc)
        self.enc_b.place(relx=0.12, rely=0.69, height=34, width=157)
        self.enc_b.configure(activebackground="#d9d9d9")
        self.enc_b.configure(activeforeground="#000000")
        self.enc_b.configure(background="#8080ff")
        self.enc_b.configure(disabledforeground="#a3a3a3")
        self.enc_b.configure(font=font11)
        self.enc_b.configure(foreground="#ffffff")
        self.enc_b.configure(highlightbackground="#d9d9d9")
        self.enc_b.configure(highlightcolor="black")
        self.enc_b.configure(pady="0")
        self.enc_b.configure(text='''ENCRYPT''')
        self.enc_b.configure(width=157)

        self.dec_b = Button(top,command=dec)
        self.dec_b.place(relx=0.63, rely=0.69, height=34, width=157)
        self.dec_b.configure(activebackground="#d9d9d9")
        self.dec_b.configure(activeforeground="#000000")
        self.dec_b.configure(background="#8080ff")
        self.dec_b.configure(disabledforeground="#ffffff")
        self.dec_b.configure(font=font11)
        self.dec_b.configure(foreground="#ffffff")
        self.dec_b.configure(highlightbackground="#d9d9d9")
        self.dec_b.configure(highlightcolor="black")
        self.dec_b.configure(pady="0")
        self.dec_b.configure(text='''DECRYPT''')
        self.dec_b.configure(width=157)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.15, rely=0.53, height=21, width=130)
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Enter Encryption Code :''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.63, rely=0.53, height=21, width=128)
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Enter Decryption Code:''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.09, rely=0.62, height=21, width=37)
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''(0-25)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.17, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-25)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.26, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-29)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.34, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-9)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.58, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-25)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.66, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-25)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.75, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-29)''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.83, rely=0.62, height=21, width=37)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(0-9)''')

        self.Msg_enc = Message(top,textvariable=encMsg)
        self.Msg_enc.place(relx=0.1, rely=0.82, relheight=0.08, relwidth=0.31)
        self.Msg_enc.configure(background="#d9d9d9")
        self.Msg_enc.configure(foreground="#000000")
        self.Msg_enc.configure(highlightbackground="#d9d9d9")
        self.Msg_enc.configure(highlightcolor="black")
        self.Msg_enc.configure(text='''Encryption status : Succcessfull or Failed''')
        self.Msg_enc.configure(width=180)

        self.Msg_dec = Message(top,textvariable=decMsg)
        self.Msg_dec.place(relx=0.61, rely=0.82, relheight=0.08, relwidth=0.31)
        self.Msg_dec.configure(background="#d9d9d9")
        self.Msg_dec.configure(foreground="#000000")
        self.Msg_dec.configure(highlightbackground="#d9d9d9")
        self.Msg_dec.configure(highlightcolor="black")
        self.Msg_dec.configure(text='''Decryption status : Succcessfull or Failed''')
        self.Msg_dec.configure(width=180)






if __name__ == '__main__':
    vp_start_gui()



